# Global LLM configuration
# model = "claude-3-5-sonnet"
# base_url = "https://api.openai.com/v1"
# api_key = "sk-..."
# max_tokens = 4096
# temperature = 0.0

# [llm] #AZURE OPENAI:
# api_type= 'azure'
# model = "YOUR_MODEL_NAME" #"gpt-4o-mini"
# base_url = "{YOUR_AZURE_ENDPOINT.rstrip('/')}/openai/deployments/{AZURE_DEPOLYMENT_ID}"
# api_key = "AZURE API KEY"
# max_tokens = 8096
# temperature = 0.0
# api_version="AZURE API VERSION" #"2024-08-01-preview"

# Global LLM configuration
[llm]
model = "gpt-4o-mini"
base_url = "https://api.openai.com/v1"
api_key = "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"  
max_tokens = 4096
temperature = 0.0

# Optional configuration for specific LLM models
[llm.vision]
model = "gpt-4o"
base_url = "https://api.openai.com/v1"
api_key = "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" 
